version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - REDIS_URL=redis://db:6379
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: "redis:alpine"

  frontend:
    build: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    ports:
      - "3000:3000"
